person:
  userName: 张三
  boss: true
  birth: 2021/9/6
  age: 20
  pet: {name: 汤姆,weight: 1}
  #  行内写法
  #  interests: [篮球,乒乓球,羽毛球]
  interests:
  - 长跑
  - 跳高
  - 排球
  #  行内写法
  #  animal: [阿猫,阿狗]
  animal:
  - 鹦鹉
  - 狗狗
  #  行内写法
  #  score: {english: 80,math: 90}
  score:
    english: 90
    math: 100
  #  行内写法
  #  salarys: [9980,9999.8,8088.8]
  salarys:
  - 8000.0
  - 9000.0
  #  行内写法
  #  allPets: {sick:[{name: 杰瑞,weight: 2}],health:[{name: 汤姆,weight: 1}]}
  allPets:
    sick:
    - name: 杰瑞
      weight: 2
    health:
    - name: 汤姆
      weight: 1